version: '3.4'

services:
  api-assistencia-tecnica:
    image: api-assistencia-tecnica
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
      
      # MySQL Connection String
      MySQLConnection__MySQLConnectionString: "Server=host;DataBase=AssitenciaTecnica;Uid=AssitenciaTecnicaRoot;Pwd=psw@;SslMode=none;"

      # Token Configurations
      TokenConfigurations__Audience: "AssistenciaTecnica"
      TokenConfigurations__Issuer: "https://assistenciatecnica.dvmi.com.br"
      TokenConfigurations__Secret: "ZUFW<Ts`C1@>M7V3LNsi?3efS}2CLs4dS@$F_"
      TokenConfigurations__Minutes: 60
      TokenConfigurations__DaysToExpiry: 7

      # Microsoft Authentication
      Authentication__Microsoft__ClientId: "Authentication__Microsoft__ClientId"
      Authentication__Microsoft__ClientSecret: "Authentication__Microsoft__ClientSecret"

    ports:
      - 44300:8080  # Mapeando corretamente para a porta 8080
    networks:
      - assistencia-tecnica

networks:
  assistencia-tecnica:
    driver: bridge
